### PR TITLE
Resolves #1570 Formly button type demo added

### LINKED ISSUE #1570: Button style not applied to formly type button with 17.0.13 version
**Components Involved**
Formly Type "button" 

**Expected Behavior**
Style need to be applied based on the btntype property.

**Actual Behavior**
Button displays with no styling. See screenshots for reference

**Your Environment**
Angular Version: 17.3.9
 "@gsa-sam/components": "17.0.13",
"@gsa-sam/sam-formly": "17.0.13"

**Ticket Number**
Please provide your JIRA ticket number that is dependent on this fix. If there is none, please create
one to validate the issue once the fix has been released. DO NOT provide the url, please ONLY
provide the ticket number.
IAEMOD-36747

**Additional context**
Screenshots / recordings, minimal reproduction on stackblitz, steps to reproduce, code snippets, etc.
formly-button-comp
formly-button

### PR DESCRIPTION
**Pull request by yerramshilpa**
## Description

This PR is for adding formly button type demos

https://github.com/GSA/sam-design-system/issues/1570
## Type of Change (Select One and Apply Github Label)

- [ ] Bug fix (non-breaking change which fixes an issue) -> Apply bugfix label
- [x] New feature (non-breaking change which adds functionality) -> Apply enhancement label
- [ ] Breaking change (fix or feature that would cause existing functionality to change) -> Apply breaking label

## Which browsers have you tested?
- [] Internet Explorer 11
- [ ] Edge
- [x] Chrome
- [ ] Firefox
- [ ] Safari

## Checklist:

- [ ] I have read the (https://github.comv/GSA/sam-ui-elements/blob/CONTRIBUTING.md)[CONTRIBUTING.md] document.
- [ ] My code passes the automated linter.
- [ ] This code has been reviewed by another team member and passes the reviewer checklist found in (https://github.comv/GSA/sam-ui-elements/blob/CONTRIBUTING.md)[CONTRIBUTING.md]
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] My code is 508 compliant as tested by AMP and JAWS
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

File: libs/documentation/src/lib/storybook/formly/formly-button/formly-button-basic/formly-button-basic.component.ts [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+  fields: FormlyFieldConfig[] = [
+     {
+      
+      fieldGroup: [
+        {
+          className: 'desktop:grid-col-12 tablet:grid-col-12',
+          type: 'button',
+          props: {
+            enableInput: true,
+           // btnIcon: 'plus-circle',
```
Comment (cwolf10) [inline libs/documentation/src/lib/storybook/formly/formly-button/formly-button-basic/formly-button-basic.component.ts:24]: Is there a reason to keep these comments in the demo code?

File: libs/documentation/src/lib/storybook/formly/formly-button/formly-button.stories.ts [hunk 2]
```diff
@@ -0,0 +1,123 @@
...
+import { moduleMetadata, Meta, StoryObj, applicationConfig } from '@storybook/angular';
+import { generateConfig, generateStackblitzLink } from 'libs/documentation/src/sandbox/sandbox-utils';
+
+import { FormlyButtonIntroductionModule } from './formly-button-introduction/formly-button-introduction.module';
+
+import { FormlyButtonBasicModule } from './formly-button-basic/formly-button-basic.module';
+import { FormlyButtonOptionsModule } from './formly-button-options/formly-button-options.module';
+import { importProvidersFrom } from '@angular/core';
+import { FormlyButtonConfigurableModule } from './formly-button-configurable/formly-button-configurable.module';
+const disable = {
```
Comment (cwolf10) [inline libs/documentation/src/lib/storybook/formly/formly-button/formly-button.stories.ts:15]: I'm pretty sure this var isn't being used, if so it can be deleted.

File: libs/documentation/src/lib/storybook/formly/formly-button/formly-button-basic/formly-button-basic.component.ts (hunk 1 above)
Comment (yerramshilpa) [reply libs/documentation/src/lib/storybook/formly/formly-button/formly-button-basic/formly-button-basic.component.ts]: Removed unused code

File: libs/documentation/src/lib/storybook/formly/formly-button/formly-button.stories.ts (hunk 2 above)
Comment (yerramshilpa) [reply libs/documentation/src/lib/storybook/formly/formly-button/formly-button.stories.ts]: Removed unused code

**Review by cwolf10 — APPROVED** [review]
